version: '2'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: swi
      MYSQL_USER: swi
      MYSQL_PASSWORD: password
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redis:/data"
  elasticsearch:
    build: elasticsearch
    environment:
      discovery.type: single-node
      cluster.name: swi-cluster
      bootstrap.memory_lock: "true"
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "9200:9200"
    expose:
      - 9300
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
  api:
    depends_on:
      - mysql
    build: src
    links:
      - mysql
      - elasticsearch
    expose:
      - 8000
    volumes:
      - ./src:/var/www/app
    command: "run reload"
  nginx:
    image: nginx
    depends_on:
      - api
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  mysql:
    driver: local
  elasticsearch:
    driver: local
  redis:
    driver: local
